struct test3 {
    string yay;
};

struct test2 {
    test3 woo[2][2];
};

struct test1 {
    test2 t2;
    test3 t3[2];
};

test1 add(test1 a);
int subtract(int x, int y);
int multiply(int x, int y);
int divide(int x, int y);

